/************************************************************************
*
*   Module name         : XTypes.h
*
*   Module description  :
*       This header file defines new types and symbols for common used
*
*   Project             : Generic
*
*   Target dependency   : Any C compiler
*
*   Author              : Richard Shen
*
*   Creation date       : 18/08/1992
*
************************************************************************/
#ifndef XTYPES_H
#define XTYPES_H

#include <stddef.h>

typedef unsigned char      uchar;
typedef unsigned int       uint;
typedef unsigned long      ulong;

#endif /* XTYPES_H */
